src/app/login/page.tsx
이메일과 비밀번호 유효성 검사
---
---
---
---
=> ✨ Feat: 이메일과 비밀번호 유효성 검사

src/app/components/common/PrgressBar.tsx, src/app/components/routine/CalendarBar.tsx, src/app/components/routine/Routine.tsx, src/app/components/routine/YellowCheckIcon.tsx, src/app/routine/page.tsx
루틴페이지 퍼블리싱 완료
(진행률바는 회원가입페이지에 변화없는선에서 수정했습니다)
---
캘린더 바텀시트부분은 작업중입니다
---
date-fns
---
혹시 +버튼 위치가 거슬리신다면 추후 푸터 생기면 그거 기준으로 수정예정,,,
---
=> 💄 Style: 루틴페이지 퍼블리싱

src/app/(auth)/find-password/layout.tsx, src/app/(auth)/find-password/page.tsx, src/app/(auth)/find-password/reset/page.tsx, src/app/(auth)/login/page.tsx, src/app/components/common/ui/NextBtn.tsx, src/store/useFindPwdStore.ts
비밀번호 찾기? 변경 페이지 퍼블리싱 작업 완료했습니다
---
---
---
---
=> 💄 Style: 로그인 -> 비번 변경페이지 퍼블리싱 완료

src/app/components/common/ui/BottomNav.tsx, src/app/layout.tsx, src/app/page.tsx, src/app/routine/page.tsx
- 하단내비
- 글쓰기 버튼 조정
---
---
---
---
상아님이 말씀해주신 글쓰기 버튼 조정도 같이 했습니당
=> ✨ Feat: 하단 내비게이션 UI 및 layout 연동

package-lock.json, package.json, src/app/components/report/CategoryDistributionChart.tsx, src/app/components/report/CompletionRateChart.tsx, src/app/components/report/MonthSummary.tsx, src/app/components/report/ReportLayout.tsx, src/app/components/report/TopRoutineRanking.tsx, src/app/report/page.tsx
리포트 퍼블리싱 했습니다 했다고요
---
---
`recharts`
---
---
=> 💄 Style: 리포트 페이지 퍼블리싱

src/app/admin/category/page.tsx, src/app/components/admin/CategoryEdit.tsx, src/app/components/common/CategoryGrid.tsx, src/app/components/common/ui/Donut.tsx, src/app/components/main/Profile.tsx, src/app/components/main/Quest.tsx, src/app/page.tsx, src/app/routine/page.tsx
전체 페이지 검토하면서 아주 사소한 스타일 수정 몇개 했습니다!
---
---
---
---
=> 💄 Style: 페이지별 사소한 스타일 수정

package-lock.json, package.json, src/api/badges.ts, src/api/categories.ts, src/api/items.ts, src/app/(protected)/collection/page.tsx, src/app/(protected)/mypage/edit-character/page.tsx, src/app/(protected)/mypage/page.tsx, src/app/(protected)/routine/add-category/page.tsx, src/app/(protected)/routine/edit-category/page.tsx, src/app/(protected)/routine/edit-subcategory/page.tsx, src/app/(protected)/shop/layout.tsx, src/app/(protected)/shop/page.tsx, src/app/components/collection/CollectionItem.tsx, src/app/components/common/CategoryBottomSheetContainer.tsx, src/app/components/common/CategoryGrid.tsx, src/app/components/common/SubCategoryGrid.tsx, src/app/components/common/ui/CategoryNameInputBottomSheet.tsx, src/app/components/common/ui/Header.tsx, src/app/components/shop/ItemCard.tsx, src/app/components/shop/ShopHeader.tsx
=> ✨ Feat: 카테고리 관련 API

src/api/api.ts, src/app/(protected)/mypage/change-userinfo/userinfo/page.tsx
=> 🐛 Fix: 닉네임 중복확인 오류 수정

src/api/member.ts, src/app/(protected)/mypage/edit-character/page.tsx, src/app/(protected)/mypage/page.tsx, src/app/components/main/Profile.tsx, src/store/UserStore.ts
스웨거에 맞춰 보유포인트 api 주소 수정했습니다
추가로 캐릭터 꾸미기 아이템 관련 api도 스웨거에 맞게 수정했습니다
---
---
---
---
=> 🐛 Fix: 보유포인트 api 주소 수정 & 아이템 장착 부분 api 수정

src/api/badges.ts, src/app/(protected)/collection/page.tsx, src/app/components/collection/CollectionItem.tsx
뱃지 장착 api 연결했습니다 
---
---
---
---
일단 도감페이지 디자인이 확정되진 않아서 현재 디자인에서 장착api만 연결해놨습니다. 추후 디자인 수정되면 회원 보유중 뱃지 api 추가로 연결하겠습니다.
+ 회원정보 불러오기에서 장착중인 뱃지도 아직 스웨거에 업데이트 되지 않아서 그것도 추후에 연결예정
=> ✨ Feat: 뱃지 장착 api 연결

src/api/admin/adminItems.ts
* 아이템 삭제 API 함수 메서드 수정했습니다
* 실수~~
---
---
---
---
=> 📝 Chore: 아이템 삭제 API 함수 메서드 수정

src/api/categories.ts, src/app/(protected)/routine/add-category/page.tsx, src/app/(protected)/routine/edit-category/page.tsx, src/app/(protected)/routine/edit-subcategory/page.tsx, src/app/components/common/CategoryBottomSheetContainer.tsx, src/app/components/common/SubCategoryGrid.tsx, types/types.ts
* 카테고리 관련 API 스웨거 업데이트 내용 기반으로 수정하였습니다
---
---
---
https://github.com/user-attachments/assets/99d04738-8566-471b-9113-d9fba335382f
---
* 청소 / 정리 카테고리 아이콘 스웨거에 아이콘 지정을 안 해줘서 안 보임
* 헤더 편집 버튼 클릭하면 사용자가 생성한 커스텀 카테고리에만 삭제 가능한 x 버튼 생성되는데, 현재 커스텀 카테고리가 없어서 아무런 변화 없음
=> 🐛 Fix: 카테고리 관련 API 스웨거 업데이트 수정

src/app/(protected)/shop/page.tsx, src/app/components/shop/ItemCard.tsx
* 상점 아이템 API 관련하여 스웨거 업데이트 내용으로 수정하였습니다.
---
---
---
* UI 변경 사항 없음
---
=> 🐛 Fix: 상점 아이템 관련 API 스웨거 업데이트 수정

src/api/badges.ts, src/app/(protected)/collection/page.tsx, types/general.ts
* 메인 페이지 > 도감 업적 조회와 보상 수령 API Tanstack Query 적용했습니다.
---
---
---
---
* UI 상 변경 없음.
* 다만, 스웨거에서 보상 수령 후 isReceived 테스트가 불가하여 보상 받기 버튼 클릭 후에도 보상 받기 버튼으로 보여짐.
=> 🔨 Refactor: 도감 페이지 업적 조회 & 보상 수령 API Tanstack Query 적용

src/api/admin/adminWithdraw.ts, src/app/admin/page.tsx, src/app/admin/withdraw/[idx]/page.tsx, src/app/admin/withdraw/layout.tsx, src/app/admin/withdraw/page.tsx, src/app/components/admin/withdraw/Calendar/CalendarDate.tsx, src/app/components/admin/withdraw/Calendar/DatePicker.tsx, src/app/components/admin/withdraw/Calendar/DatePickerWrapper.tsx, src/app/components/admin/withdraw/Calendar/Month.tsx, src/app/components/admin/withdraw/MultiLineChart.tsx
관리자 탈퇴사유분석 페이지 퍼블리싱 완료했습니다 
(api도 연결하긴했는데 아직 완성이 아니라 탈퇴사유 불러오기만 연결. 그래프부분 기간별 조회는 추후 api 완성되면 수정예정)
---
---
dayjs
---
---
=> ✨ Feat: 관리자 탈퇴사유분석 페이지 퍼블리싱 완료 & api 연결

src/api/member.ts, src/app/components/main/Quest.tsx, src/app/components/main/QuestList.tsx
퀘스트 페이지 조회 & 보상 수령 API Tanstack Query 적용했습니다
---
---
---
---
=> 🔨 Refactor: 퀘스트 페이지 조회 & 보상 수령 API Tanstack Query 적용

src/api/categories.ts, src/app/(protected)/routine/add-category/AddCategoryLayout.tsx, src/app/(protected)/routine/add-category/page.tsx, src/app/(protected)/routine/edit-subcategory/EditSubcategoryLayout.tsx, src/app/(protected)/routine/edit-subcategory/page.tsx, src/app/components/common/CategoryBottomSheetContainer.tsx, types/general.ts
* 수정된 스웨거 기반으로 유저 카테고리 조회/ 생성/ 삭제/ 수정 API Tanstack Query 적용하였습니다.
* 현재 스웨거 DB에 커스텀 카테고리가 없어서, 코드는 존재하나 커스텀 카테고리에 대한 생성, 삭제, 수정 테스트는 되지 않았습니다.
---
---
---
* UI 변경 없음
---
=> 🔨 Refactor: 유저 카테고리 조회/ 생성/ 삭제/ 수정 API Tanstack Query 적용

package-lock.json, package.json, src/api/admin/adminCategories.ts, src/app/admin/category/add-category/page.tsx, src/app/admin/category/layout.tsx, src/app/admin/category/page.tsx, src/app/components/admin/CategoryEdit.tsx, src/app/components/common/CategoryGrid.tsx
* 관리자 카테고리 조회/ 생성/ 삭제/ 수정 API Tanstack Query 적용했습니다.
---
* 카테고리 추가 시 카테고리 이름과 이모지를 모두 선택해야 추가될 수 있도록 조건 검사를 걸어두었는데, 초기 한 번만 조건 검사가 되고, 리렌더링 하지 않으면 조건 검사가 동작하지 않는 문제가 있습니다. 
---
---
* UI 변경사항 없음
---
=> 🔨 Refactor: 관리자 카테고리 조회/ 생성/ 삭제/ 수정 API Tanstack Query 적용

src/api/auth.ts, src/api/member.ts
=> 🐛 Fix: 로그아웃 상태에서 메인페이지 접근 시 로그인 되는 코드 수정

src/app/(protected)/mypage/notification/page.tsx, src/app/(protected)/routine/add-routine/page.tsx, src/app/components/common/Noti.tsx, src/app/components/common/Notification.tsx, src/app/components/common/ui/Header.tsx
=> 💄 Style: 알림 팝업 퍼블리싱 개선

src/api/auth.ts, src/app/(protected)/mypage/change-userinfo/userinfo/page.tsx, src/app/(protected)/mypage/page.tsx, src/app/components/signup/UserInfo.tsx
=> 🐛 Fix: 인증 API 이메일 중복 / 로그아웃 수정

src/app/(protected)/collection/page.tsx, src/app/(protected)/mypage/change-userinfo/userinfo/address/page.tsx, src/app/(protected)/mypage/change-userinfo/userinfo/page.tsx, src/store/UserEditStore.ts
주소 재설정시 공백 오류 수정 & 닉네임 중복확인 상태관리 추가
+ 장착 상태변경 시 프로필에서 바로 최신화
---
---
---
---
=> 🐛 Fix: 주소 재설정시 공백 오류 수정 & 닉네임 중복확인 상태관리 추가

src/app/components/common/ui/Header.tsx, src/hooks/useNotifications.ts
=> 🐛 Fix: 웹소켓 연결 실패 수정

src/app/components/common/ui/Header.tsx, src/hooks/useNotifications.ts
=> 🐛 Fix: 웹소켓 연결 서버 주소 수정

src/app/(protected)/collection/page.tsx, src/app/(protected)/mypage/change-userinfo/userinfo/page.tsx, src/app/(protected)/mypage/edit-character/page.tsx, src/app/components/main/Profile.tsx, src/app/components/main/QuestList.tsx
=> ✨ Feat: 퀘스트, 프로필(포인트, 아이템, 뱃지) 낙관적 업데이트 코드 추가

src/api/routine/handleRoutine.ts
=> ✨ feat: 루틴 완료 시 포인트 낙관적 업데이트 적용

src/app/(protected)/mypage/page.tsx
=> 🐛 fix: 로그아웃 시에도 이전 사용자 정보 보이는 문제 해결

src/api/routine/handleRoutine.ts, src/app/components/main/Profile.tsx
코드 다시 확인해서 날아갔던 코드들 다시 추가했습니다 (캐릭터 꾸미기, 포인트)
제발 이번엔 추가 제대로 되기를,,,
---
---
---
---
=> 🐛 Fix: 날아갔던 코드들 다시 추가 (캐릭터 꾸미기, 포인트)

src/api/routine/handleRoutine.ts
=> 🐛 Fix: 루틴 완료/미완료 시 도감 업데이트 반영

src/api/routine/handleRoutine.ts, src/app/components/common/alert/AlertModal.tsx, src/app/components/main/Profile.tsx
프로필에서 캐릭터 옷입히기 코드 사라짐, 루틴 완료/취소 시 포인트 낙관적 업데이트 수정
(왜 자꾸 프로필에서 캐릭터 옷입히기 코드가 사라지는지 의문입니다ㅜ)
---
---
---
---
=> 🐛 fix: 프로필에서 캐릭터 옷입히기 코드 사라짐, 루틴 완료/취소 시 포인트 낙관적 업데이트 수정

src/app/(protected)/home/page.tsx, src/app/(protected)/mypage/change-userinfo/check-password/page.tsx, src/app/(protected)/mypage/change-userinfo/page.tsx, src/app/(protected)/mypage/page.tsx, src/store/UserStore.ts
소셜은 배포되고 확인가능한거 같아서 확인은 아직 못해봤습니다!
---
---
---
---
=> 🔨 Refactor: 소셜로그인 시 회원정보 변경 경로 수정, 비밀번호 수정 접근 X
